version: '3.9'

services:
  database:
    image: ${DB_IMAGE}:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app_network

  app:
    image: node:20
    container_name: nestjs_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_PORT: ${APP_PORT}
    command: npm run start:prod
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
